### ISSUE TITLE
Inactivate human biomass reaction (MAR13082) by default

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Mouse-GEM#11]
### Description of the issue:
The default objective for Mouse-GEM is maximization of the "biomass components" reaction (MAR00021). The model also includes the human-specific biomass reaction (MAR13082). Although the human-specific biomass reaction (MAR13082) is not set as the objective, it should be closed (lb = ub = 0) by default so that only one biomass reaction is "active" by default.

**Note:** this fix should probably also apply to Rat-GEM and the other standard-GEM animal models.

#### Expected feature/value/output:
`ub` of MAR13082 set to zero.

#### Current feature/value/output:
`ub` of MAR13082 is 1000.

**I hereby confirm that I have:**
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
@JonathanRob aim to fix this in the next release

**Comment by haowang-bioinfo** [comment]
this has been fixed in v1.3
