### ISSUE TITLE
It seems the annotation is empty in Mouse-GEM - causes problems in addRxns

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/Mouse-GEM#12]
### Description of the issue:
mouseGEM.annotation gives:

ans = 

  struct with fields:

      authorList: ''
           email: ''
    organization: ''
        taxonomy: ''
       sourceUrl: ''
            note: ''
       defaultLB: ''
       defaultUB: ''
the defaultLB and UB are used in addRxns, and generates a messed up vector for model.ub, it looks like incorrect memory or something, or that the whole vector is casted to char.

#### Expected feature/value/output:
Fill these in, -1000 and 1000 is used in Human-GEM

#### Current feature/value/output:
empty

#### Reproducing these results:

```matlab

```

**I hereby confirm that I have:**
- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [ ] Done this analysis in the `master` branch of the repository
- [ ] Checked that a similar issue does not exist already
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by johan-gson** [comment]
I loaded the model from the .mat file.

**Comment by mihai-sysbio** [comment]
The `default` fields seem to be particular to the .mat file, as they do not show up in any of the other file formats. Also, this issue seems to be stemming from Human-GEM, so perhaps it should be transferred there?

**Comment by johan-gson** [comment]
Hmm, ok. The problem doesn't exist in Human-GEM. An alternative is to fix it in RAVEN (i.e. check these fields more carefully before using them).

**Comment by mihai-sysbio** [comment]
Right, it doesn't exist in Human-GEM. My thinking is that whatever is done there with these default fields is not really robust since it is inconsistent across the different file formats. But you're right, it might be that the fix belongs in RAVEN. I'm pinging @edkerk in case he knows something about this, if it would make sense to report this in RAVEN.

**Comment by johan-gson** [comment]
I think I know how to fix it, it would be a small change in AddRxns. It looks like this (see below). So, an additional check if isempty(newModel.annotation.defaultLB) would probably do the trick. I have not tested if isempty catches this, but I would think so. The same needs to be done for defaultUB.

if isfield(newModel,'annotation') & isfield(newModel.annotation,'defaultLB')
    newLb=newModel.annotation.defaultLB;
else
    newLb=-inf;
end

**Comment by haowang-bioinfo** [comment]
will look into this when making new release of `Mouse-GEM`

**Comment by haowang-bioinfo** [comment]
this has been fixed in v1.3
