### ISSUE TITLE
feat: use `tsv` file to archive ortholog pairs

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Mouse-GEM#15]
### Description of the issue:
* As discussed in #14, a better of storing ortholog pairs would be in `tsv`, instead of raw `json` file that is super large and hard to track

#### Expected feature/value/output:
* Replace `json` with `tsv` file while updating ortholog pairs between human and mouse

**I hereby confirm that I have:**
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
That sounds very useful. I'm just wondering what is the standard way to do this, if there is one.

**Comment by haowang-bioinfo** [comment]
> I'm just wondering what is the standard way to do this, if there is one.

not heard of

**Comment by haowang-bioinfo** [comment]
here I close this issue that has been resolved PRs [#482](https://github.com/SysBioChalmers/Human-GEM/pull/482) in Human-GEM and 81890bd6569ae3b6a3158f30cdba787d3ca97d8b in Mouse-GEM.
