### ISSUE TITLE
.mat model should not contain full annotation information

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Mouse-GEM#16]
### Description of the issue:
The .mat model file (`Mouse-GEM.mat`) on the main branch contains all the additional metabolite and reaction annotations from the correspond .tsv files (likely added by `annotateGEM` function).

**Note:** The same issue is present for Fruitfly-GEM, so I suspect all the animal GEMs may need to be checked for this issue.

#### Expected feature/value/output:
The .mat version should not contain this additional annotation information (see `Human-GEM.mat` for comparison).

**I hereby confirm that I have:**
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
@JonathanRob thanks for making this issue.

Please let me know if the aim is to make animal GEMs to be consistent with HumanGEM, or else? if there was a discussion about this before?

**Comment by JonathanRob** [comment]
I don't think they need to be identical, but they should follow the same rules that are in place to prevent problems. Currently, loading the model from the .yml file produces a model that is different than if loaded from the .mat file. Also, the additional fields present in the .mat file are not recognized by most functions in e.g. RAVEN and therefore cause problems.
