### ISSUE TITLE
CHEBI:8100 in wrong column in metabolites.tsv

### ISSUE THREAD

**Issue by SchSascha** [SysBioChalmers/Mouse-GEM#21]
### Description of the issue:
*Try to be as clear as possible: Is it something wrong/missing in the model? Is it a simulation issue? PLEASE DELETE THIS LINE.*
I imported metabolites.tsv into R and while doing so, stumbled upon this small misplacement.
CHEBI:8100 encoding phlac is in column 11 instead of column 3 (row 6717).
Figured it might be helpful, in case there is a bigger systematic parsing issue behind it. 
This is also present in the latest [release ](https://github.com/SysBioChalmers/Mouse-GEM/releases/tag/v1.3.1).

#### Reproducing these results:
```r
library("tidyverse")
read_tsv("model/metabolites.tsv")
```

**I hereby confirm that I have:**
- [x] Done this analysis in the `main` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
@SchSascha thank you very much for spotting this error, which will be fixed as soon as possible.

**Comment by haowang-bioinfo** [comment]
fixed in [#460](https://github.com/SysBioChalmers/Human-GEM/pull/460) of Human-GEM
