### ISSUE TITLE
no gene association found in xml model

### ISSUE THREAD

**Issue by Kai6662** [SysBioChalmers/Mouse-GEM#24]
### Description of the issue:
Error in loadGSC("/mnt/workspace_dierickx/kcui/mouse-gem/Mouse-GEM/model/Mouse-GEM.xml") : no gene association found

Hi,

I am using mouse-GEM model. I load xml file using loadGSC function in R. But there is no gene association found. 

Do you know what is the problem?

Thanks in advance.

Kai

**Comment by Kai6662** [comment]
Hi,

My OS environment is SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux; my software is R;  and the package is piano. 
Piano package can do reporter metabolites analysis using Model.xml. Then I tried to load mouse.xml using loadGSC function.

Best
Kai

**Comment by Kai6662** [comment]
Based on piano vignette, loadGSC function  is  to load a gene set collection from a genome-scale metabolic model. It looks like the function included open the model and collect gene set.

**Comment by mihai-sysbio** [comment]
Based on [the documentation of `loadGSC`](https://www.rdocumentation.org/packages/piano/versions/1.12.0/topics/loadGSC), in principle loading a model should work. So I'm wondering now if perhaps it has to do with some implicitly expected gene annotation.

**Comment by Kai6662** [comment]
Do you know some alternative reporter metabolites analysis tools?  So that I can use your mouse-GEM model well.  I only knew piano can do that.

**Comment by Kai6662** [comment]
Could you recommend me a software to do reporter metabolites analysis using your mouse model?  I would appreciate it.

**Comment by haowang-bioinfo** [comment]
I think piano is good for reporter metabolites analysis.

To extract GSC from MouseGEM, you may try the following code and this [repo](https://github.com/JonathanRob/GeneSetAnalysisMatlab):

```matlab
# Load MouseGEM from your local computer after cloning the repo
load('../Mouse-GEM/model/Mouse-GEM.mat')

# Extract MouseGEM GSC after cloning and installing the GeneSetAnalysisMatlab repo
extractMetaboliteGSC(model, true, 'mouseGSC.txt')
```

Then the "mouseGSC.txt" file can used with piano for downstream analysis.

**Comment by Kai6662** [comment]
Thank you so much! It is working!

**Comment by haowang-bioinfo** [comment]
feel free to reopen
