### ISSUE TITLE
How to generate the Mouse-GEM.xlsx

### ISSUE THREAD

**Issue by ErikaKvalem** [SysBioChalmers/Mouse-GEM#26]
### How to generate the Mouse-GEM.xlsx?
I have browsed the Human-GEM and found the model to be provided in different formats including .mat, .yml and .xlsx . But for other of GEM (worm, mouse) this format is not available. Is there a reason for that? I have tried to create it myself using the Human-GEM.xlsx as a reference but the filed names seem different and I am not sure of the correspondance. What would be the way to convert from .mat to xlsx in  this case? Thank you.

**Comment by mihai-sysbio** [comment]
Hi @ErikaKvalem, thank you for the question. In short, `xlsx` is a format with unknown user base. Being a binary format, it would increase the repository size significantly.
The [RAVEN toolbox](https://github.com/SysBioChalmers/raven) has a function to export a model to `xlsx`, see [exportToExcelFormat](https://sysbiochalmers.github.io/RAVEN/doc/io/exportToExcelFormat.html). Hope this helps!

**Comment by mihai-sysbio** [comment]
Closing this as presuming issue is now resolved.

**Comment by mihai-sysbio** [comment]
Closing this as presuming issue is now resolved.
