### ISSUE TITLE
review .standard-GEM.md file

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/Mouse-GEM#5]
### Description of the issue:
The file in question starts with:
> This document serves as a checklist for creating an open source genome-scale metabolic model (GEM) on GitHub.

I propose the revision of this file by check-marking all sections that apply. Also, as part of this step, the `README` should also be revised.

#### Expected feature/value/output:
A revised `standard-GEM` file, with all revelant boxes checked, and an improved `README`.

**I hereby confirm that I have:**
- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [ ] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio thanks for spotting this, welcome fix it.

**Comment by Hao-Chalmers** [comment]
feel free to reopen this
